### PR TITLE
Removing paranoiaCheck as fix is now in chrome

### PR DESCRIPTION
**Pull request by jonathanKingston**
@stefanpenner and @rwjblue as we now have a Chrome that has a stable SRI this should be safe to push in.

### CODE REVIEW

**Comment by stefanpenner** [comment]
:+1:

**Comment by jonathanKingston** [comment]
@stefanpenner you know you should be drinking etc right?

**Comment by jonathanKingston** [comment]
Ah tests need fixing :(

**Comment by stefanpenner** [comment]
> @stefanpenner you know you should be drinking etc right?

I could say the same ;)

**Comment by jonathanKingston** [comment]
@stefanpenner I am now, so will leave this until we are less drunk. Patch seems fine will await less holiday mode.

**Pull request merged**
